### ISSUE TITLE
doubts about the test restoration results in the paper

### ISSUE THREAD

**Issue by xzltc** [ryo-abiko/CANet#1]
Hi! thanks for you paper, the paper was cool. 

but I have some doubts about the test restoration result.
like in table3 and table4, The AEF[17] results in ISTD+ and ISTD shadow part were 8.77 and 10.05, respectively. But the original paper utilize the RMSE evaluation metric and color space same in LAB were 6.5 and 7.77, there is a relatively obvious difference between the two result,So it is used the evaluation metric in SID[14] that causes the relatively obvious difference in the results?

**Comment by ryo-abiko** [comment]
Hi, thank you for reading my paper.

Yes, I understand that our values in the paper are different from the values in the comparison methods. It is caused because we use different code for the evaluation, implemented by ourselves (Please see evaldata.py). The code used in SID and other papers is calculating MAE instead of RMSE. This issue is also mentioned by the author of SID (Please see https://github.com/cvlab-stonybrook/SID).

**Comment by xzltc** [comment]
thanks for you reply!  I notice it this days, I download the AEF、SID and other test result and run the evaluation code, the result is same as the paper. It is also strange why previous all make the same obvious mistakes before.

**Comment by ryo-abiko** [comment]
Thank you for your testing! I am also wondering why the incorrect evaluation code continues to be used in this research area.

**Comment by xzltc** [comment]
yeah,I agree that it is still necessary to correct it.
by the way I found the ISTD、SDR test result were same, but the ISTD+ with you provide in Google Drive result  I got were shadow: 11.33, Non-shadow: 9.07, All: 9.05. I unclear what cause it.
thanks for you reply, good luck with your studies.

**Comment by ryo-abiko** [comment]
I tested in my environment.
```
$ python evaldata.py \
>     --method_name CANet \
>     --dataset_name ISTDplus \
>     --resized 1
=========
Dataset: ISTDplus / Method: CANet / Resize : 256x256
== RMSE ==
shadow: 8.14, Non-shadow:4.81, All: 5.59
== MAE ==
shadow: 6.22, Non-shadow:3.19, All: 3.66
== PSNR ==
All: 31.97
== SSIM ==
All: 0.933
=========
```
In my environment, It seems that the result is valid.

When I compared the result of ISTDplus with ISTD (not plus) dataset, I got the same result as you got.
```
$ python evaldata.py \
>     --method_name CANetplus \
>     --dataset_name ISTD \
>     --resized 1
=========
Dataset: ISTD / Method: CANetplus / Resize : 256x256
== RMSE ==
shadow: 11.33, Non-shadow:9.07, All: 9.51
== MAE ==
shadow: 9.54, Non-shadow:7.61, All: 7.82
== PSNR ==
All: 25.22
== SSIM ==
All: 0.921
=========
```

ISTDplus dataset is not public accessible, so you need to create a new dataset with applying [MATLAB code](https://www3.cs.stonybrook.edu/~cvl/projects/SID/index.html) provided by the SID authors.

**Comment by xzltc** [comment]
Oops! after run MATLAB code to ISTD test gt image, I got the correct result. Thanks a lot!
